### ISSUE TITLE
Выкатить демонстрационный релиз

### ISSUE THREAD

**Issue by YuriSilenok** [Exactpro/jackfish#1]
Добрый день.

Могли бы Вы выпустить релиз этого продукта.
Это необходимо для демонстрации правильной архитектуры автоматической тестовой библиоткеки.

Спасибо.
Юрий.

**Comment by ManualTester** [comment]
When is this product expected to lease?

**Comment by YuriSilenok** [comment]
This product will be required no earlier than September 1, 2019.
